[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
optimizer = true
optimizer_runs = 500
via_ir = true
solc = "0.8.30"
bytecode_hash = "none"
cbor_metadata = false
always_use_create_2_factory = true
fs_permissions = [{ access = "read", path = "./addresses" }]


# Resolve external imports
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
base = "https://mainnet.base.org"

[profile.ci]
fuzz = { runs = 256 }
verbosity = 2

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
